---
# handlers file for .
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
    name: tomcat
    state: start
    
- name: restart tomcat instance
  service:
    name: "{{ instance_name }}"
    state: restarted
        